# Generated by Django 4.2.30 on 2026-06-05 08:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transactions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('budgets', '0002_initial'),
        ('assistant', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpendingInsight',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('insight_type', models.CharField(choices=[('spending_increase', 'Spending Increase'), ('spending_decrease', 'Spending Decrease'), ('new_merchant', 'New Merchant'), ('category_trend', 'Category Trend'), ('subscription_found', 'Subscription Found'), ('budget_warning', 'Budget Warning'), ('anomaly_detected', 'Anomaly Detected'), ('savings_opportunity', 'Savings Opportunity'), ('recurring_pattern', 'Recurring Pattern'), ('income_change', 'Income Change')], max_length=30)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('actionable_advice', models.TextField(blank=True)),
                ('supporting_data', models.JSONField(blank=True, default=dict)),
                ('is_read', models.BooleanField(default=False)),
                ('is_dismissed', models.BooleanField(default=False)),
                ('is_actioned', models.BooleanField(default=False)),
                ('valid_from', models.DateField()),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('related_budgets', models.ManyToManyField(blank=True, to='budgets.budget')),
                ('related_subscriptions', models.ManyToManyField(blank=True, to='assistant.subscription')),
                ('related_transactions', models.ManyToManyField(blank=True, to='transactions.transaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spending_insights', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'spending_insights',
                'ordering': ['-priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SavingsRecommendation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('subscriptions', 'Subscriptions'), ('dining', 'Dining & Entertainment'), ('shopping', 'Shopping'), ('transportation', 'Transportation'), ('utilities', 'Utilities & Bills'), ('groceries', 'Groceries'), ('fees', 'Bank Fees'), ('other', 'Other')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('estimated_monthly_savings', models.DecimalField(decimal_places=2, max_digits=15)),
                ('confidence', models.FloatField(default=0.0)),
                ('action_steps', models.JSONField(blank=True, default=list)),
                ('supporting_data', models.JSONField(blank=True, default=dict)),
                ('is_implemented', models.BooleanField(default=False)),
                ('implemented_at', models.DateTimeField(blank=True, null=True)),
                ('user_feedback', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='savings_recommendations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'savings_recommendations',
                'ordering': ['-estimated_monthly_savings'],
            },
        ),
        migrations.CreateModel(
            name='MerchantEnrichment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant_name', models.CharField(db_index=True, max_length=200)),
                ('normalized_name', models.CharField(db_index=True, max_length=200)),
                ('website', models.URLField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('logo_url', models.URLField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('address', models.TextField(blank=True)),
                ('business_type', models.CharField(blank=True, max_length=100)),
                ('is_subscription_service', models.BooleanField(default=False)),
                ('subscription_pricing', models.JSONField(blank=True, default=dict)),
                ('confidence', models.FloatField(default=0.0)),
                ('source', models.CharField(default='manual', max_length=50)),
                ('lookup_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transactions.transactioncategory')),
            ],
            options={
                'db_table': 'merchant_enrichments',
                'ordering': ['-lookup_count'],
            },
        ),
        migrations.CreateModel(
            name='FinancialSummary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], max_length=20)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('total_income', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_expenses', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('net_savings', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('savings_rate', models.FloatField(default=0)),
                ('top_categories', models.JSONField(blank=True, default=list)),
                ('top_merchants', models.JSONField(blank=True, default=list)),
                ('category_breakdown', models.JSONField(blank=True, default=dict)),
                ('monthly_trend', models.JSONField(blank=True, default=list)),
                ('largest_expense', models.JSONField(blank=True, default=dict)),
                ('largest_income', models.JSONField(blank=True, default=dict)),
                ('transaction_count', models.PositiveIntegerField(default=0)),
                ('unique_merchants', models.PositiveIntegerField(default=0)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_summaries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'financial_summaries',
                'ordering': ['-period_start'],
                'unique_together': {('user', 'period', 'period_start')},
            },
        ),
        migrations.CreateModel(
            name='CashFlowProjection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('projection_date', models.DateField()),
                ('projected_income', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('projected_expenses', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('projected_balance', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('confidence_interval_low', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('confidence_interval_high', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('assumptions', models.JSONField(blank=True, default=dict)),
                ('model_version', models.CharField(default='v1', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cashflow_projections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cashflow_projections',
                'ordering': ['projection_date'],
                'unique_together': {('user', 'projection_date')},
            },
        ),
    ]
