# Generated by Django 4.2.30 on 2026-06-05 08:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('period', models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly'), ('custom', 'Custom')], default='monthly', max_length=20)),
                ('custom_start_date', models.DateField(blank=True, null=True)),
                ('custom_end_date', models.DateField(blank=True, null=True)),
                ('subcategories', models.JSONField(blank=True, default=list)),
                ('alert_threshold', models.IntegerField(choices=[(50, '50%'), (75, '75%'), (90, '90%'), (100, '100%'), (110, '110%')], default=90)),
                ('alert_enabled', models.BooleanField(default=True)),
                ('rollover_enabled', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'budgets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BudgetAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alert_type', models.CharField(choices=[('threshold', 'Threshold Reached'), ('over_budget', 'Over Budget'), ('projected_over', 'Projected Over Budget')], max_length=20)),
                ('message', models.TextField()),
                ('percentage', models.FloatField()),
                ('amount_spent', models.DecimalField(decimal_places=2, max_digits=15)),
                ('amount_budgeted', models.DecimalField(decimal_places=2, max_digits=15)),
                ('is_read', models.BooleanField(default=False)),
                ('is_dismissed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='budgets.budget')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'budget_alerts',
                'ordering': ['-created_at'],
            },
        ),
    ]
